config/routes.rb
Expertiza::Application.routes.draw do
  ###
  # Please insert new routes alphabetically!
  ###
  resources :admin, only: [] do
    collection do
      get :list_super_administrators
      get :list_administrators
      get :list_instructors
      post :create_instructor
      get :remove_instructor
      post :remove_instructor
      get :show_instructor
    end
  end

  resources :advertise_for_partner, only: %i[new create edit update] do
    collection do
      get :remove
      post ':id', action: :update
    end
  end

  resources :advice, only: [] do
    collection do
      post :save_advice
    end
  end

  resources :answer

  resources :answer_tags, only: [:index] do
    collection do
      post :create_edit
    end
  end

  resources :assessment360, only: [] do
    collection do
      # get :one_course_all_assignments
      get :all_students_all_reviews
      # get :one_student_all_reviews
      # get :one_assignment_all_students
    end
  end

  resources :assignments, except: [:destroy] do
    collection do
      get :associate_assignment_with_course
      get :copy
      get :toggle_access
      get :delayed_mailer
      get :list_submissions
      get :delete_delayed_mailer
      get :remove_assignment_from_course
    end
  end

  resources :badges, only: %i[new create] do
    collection do
      get :redirect_to_assignment
    end
  end

  resources :bookmarks, except: %i[index show] do
    collection do
      get :list
      post :save_bookmark_rating_score
    end
  end

  resources :content_pages do
    collection do
      get :list
      get ':page_name', action: :view
    end
  end

  resources :controller_actions do
    collection do
      get :list
      post ':id', action: :update
      get :new_for
    end
  end

  resources :course, only: %i[new create edit update] do
    collection do
      get :toggle_access
      get :copy
      get :view_teaching_assistants
      post :add_ta
      get :auto_complete_for_user_name
      post :remove_ta
    end
  end

  resources :eula, only: [] do
    collection do
      get :accept
      get :decline
      get :display
    end
  end

  resources :export_file, only: [] do
    collection do
      get :start
      get :export
      post :export
      post :exportdetails
    end
  end

  resources :grades, only: %i[edit update] do
    collection do
      get :view
      get :view_team
      get :view_reviewer
      get :view_my_scores
      get :instructor_review
      post :remove_hyperlink
      post :save_grade_and_comment_for_submission
    end
  end

  resources :impersonate, only: [] do
    collection do
      get :start
      post :impersonate
    end
  end

  resources :import_file, only: [] do
    collection do
      get :start
      get :show
      get :import
      post :show
      post :import
    end
  end

resources :institution, except: [:destroy] do
    collection do
      get :list
      post ':id', action: :update
    end
  end

  resources :invitations, only: %i[new create] do
    collection do
      get :cancel
      get :accept
      get :decline
    end
  end

  resources :join_team_requests do
    collection do
      post :decline
    end
  end

  resources :late_policies
  resources :markup_styles

  resources :menu_items do
    collection do
      get :move_down
      get :move_up
      get :new_for
      get :link
      get :list
    end
  end

  resources :notifications

  resources :participants, only: [:destroy] do
    collection do
      get :add
      post :add
      get :auto_complete_for_user_name
      get :delete_assignment_participant
      get :list
      get :change_handle
      get :inherit
      get :bequeath_all
      get :inherit
      get :bequeath_all
      post :update_authorizations
      post :update_duties
      post :change_handle
      get :view_publishing_rights
    end
  end

  resources :password_retrieval, only: [] do
    collection do
      get :forgotten
      get :reset_password
      post :send_password
      post :update_password
    end
  end

  resources :profile, only: %i[edit update]

  resources :publishing, only: [] do
    collection do
      get :view
      post :update_publish_permissions
      post :set_publish_permission
      get :grant
      get :grant_with_private_key
      post :grant_with_private_key
      get :set_publish_permission
    end
  end

  resources :questionnaires, only: %i[new create edit update] do
    collection do
      get :copy
      get :list
      post :list_questionnaires
      get :new_quiz
      get :select_questionnaire_type
      post :select_questionnaire_type
      get :toggle_access
      get :view
      post :create_quiz_questionnaire
      post :update_quiz
      post :add_new_questions
      post :save_all_questions
    end
  end

  resources :author_feedback_questionnaires, controller: :questionnaires
  resources :review_questionnaires, controller: :questionnaires
  resources :metareview_questionnaires, controller: :questionnaires
  resources :teammate_review_questionnaires, controller: :questionnaires
  resources :survey_questionnaires, controller: :questionnaires
  resources :assignment_survey_questionnaires, controller: :questionnaires
  resources :global_survey_questionnaires, controller: :questionnaires
  resources :course_survey_questionnaires, controller: :questionnaires
  resources :bookmarkrating_questionnaires, controller: :questionnaires

  resources :questions do
    collection do
      get :types
    end
  end

  resources :reputation_web_service, only: [] do
    collection do
      get :client
      post :send_post_request
    end
  end

  resources :response, only: %i[new create edit update] do
    collection do
      get :new_feedback
      get :view
      get :remove_hyperlink
      get :saving
      get :redirection
      get :show_calibration_results_for_student
      post :custom_create
      get :pending_surveys
      get :json
    end
  end

  resources :review_mapping, only: [] do
    collection do
      post :add_metareviewer
      get :add_reviewer
      post :add_reviewer
      post :add_self_reviewer
      get :add_self_reviewer
      get :add_user_to_assignment
      get :auto_complete_for_user_name
      get :delete_all_metareviewers
      get :delete_outstanding_reviewers
      get :delete_metareviewer
      get :delete_reviewer
      get :distribution
      get :list_mappings
      get :response_report
      post :response_report
      get :select_metareviewer
      get :select_reviewer
      get :select_mapping
      post :assign_quiz_dynamically
      get :assign_reviewer_dynamically
      post :assign_reviewer_dynamically
      get :assign_metareviewer_dynamically
      post :assign_metareviewer_dynamically
      post :automatic_review_mapping
      post :automatic_review_mapping_staggered
      # E1600
      post :start_self_review
      post :save_grade_and_comment_for_reviewer
      get :unsubmit_review
    end
  end

  resources :roles do
    collection do
      get :list
      post ':id', action: :update
    end
  end

  resources :sign_up_sheet, except: %i[index show] do
    collection do
      get :signup
      get :delete_signup
      get :add_signup_topics
      get :add_signup_topics_staggered
      get :delete_signup
      get :list
      get :signup_topics
      get :signup
      get :sign_up
      get :team_details
      get :intelligent_sign_up
      get :intelligent_save
      get :signup_as_instructor
      post :signup_as_instructor_action
      post :set_priority
      post :save_topic_deadlines
    end
  end

  resources :site_controllers do
    collection do
      get :list
      get :new_called
    end
  end

  resources :student_quizzes, only: [:index] do
    collection do
      post :student_quizzes
      post :record_response
      get :finished_quiz
      get :take_quiz
      get :review_questions
    end
  end

  resources :student_review, only: [] do
    collection do
      get :list
    end
  end

  resources :student_task, only: [] do
    collection do
      get :list
      get :view
      get '/*other', to: redirect('/student_task/list')
    end
  end

  resources :student_teams, only: %i[create edit update] do
    collection do
      get :view
      get :remove_participant
      get :auto_complete_for_user_name
    end
  end

  resources :submitted_content, only: [:edit] do
    collection do
      get :download
      get :folder_action
      get :remove_hyperlink
      post :remove_hyperlink
      get :submit_file
      post :submit_file
      post :folder_action
      post :submit_hyperlink
      get :submit_hyperlink
      get :view
    end
  end

  resources :submission_records, only: [:index]

  resources :suggestion, only: %i[show new create] do
    collection do
      get :list
      post :submit
      post :student_submit
      post :update_suggestion
    end
  end

  resources :survey_deployment, only: %i[new create] do
    collection do
      get :list
      get :reminder_thread
    end
  end

  resources :system_settings do
    collection do
      get :list
    end
  end

  resources :teams, only: %i[new create edit update] do
    collection do
      get :list
      # post ':id', action: :create_teams
      post :create_teams
      post :inherit
    end
  end

  resources :teams_users, only: %i[new create] do
    collection do
      post :list
    end
  end

  resources :tag_prompts, except: %i[new edit]
  resources :track_notifications, only: [:index]

  resources :tree_display, only: [] do
    collection do
      get :action
      post :list
      post :children_node_ng
      post :children_node_2_ng
      post :bridge_to_is_available
      get :session_last_open_tab
      get :set_session_last_open_tab
    end
  end

  resources :users, constraints: {id: /\d+/} do
    collection do
      get :list
      post :list
      get :list_pending_requested
      post ':id', action: :update
      get :show_selection
      get :auto_complete_for_user_name

app/helpers/tree_display_helper.rb
module TreeDisplayHelper
end

app/views/tree_display/_entry.html.erb
<% child_nodes = node.get_children(@sortvar,@sortorder,session[:user].id,@show,@search) %>

<%= render :partial => '/tree_display/row_header',
  :locals => {
  :depth => depth,
  :prefix => prefix,
  :rowtype => rowtype,
  :parent_node => node,
  :child_nodes => child_nodes
} %>
<% if node.get_partial_name %>
  <%if node.get_partial_name == 'courses_folder_actions' && session[:user].role_id == 6 %>
  <%else%>
    <%= render :partial => '/tree_display/actions/'+node.get_partial_name,
      :locals => {:node => node} %>
  <%end%>
<% else %>
  <%= render :partial=> '/tree_display/actions/no_actions' %>
<% end %>
<%= render :partial => '/tree_display/row_footer',
  :locals => {
  :depth => depth,
  :prefix => prefix,
  :parent_node => node,
  :child_nodes => child_nodes,
  :rowtype => nil
} %>

app/views/tree_display/_folder.html.erb
<%= render :partial=> 'row_header', :locals => {:depth => 0, :prefix => prefix, :name => name, :rowtype => rowtype, :nodes => nodes, :directory => nil, :creation_date => nil} %>
<% if action_partial %>
  <%= render :partial=> '/tree_display/actions/'+action_partial+'_folder_actions' %>
<% else %>
  <%= render :partial=> '/tree_display/actions/no_actions' %>
<% end %>
<%= render :partial=> 'row_footer', :locals => {:depth => 0, :prefix => prefix, :nodes => nodes} %>

app/views/tree_display/_listing.html.erb
<% child_nodes = node.get_children(@sortvar,@sortorder,@show,nil,nil,@search) %>
<%= render :partial => 'row_header',
  :locals => {
  :depth => depth,
  :prefix => prefix,
  :rowtype => rowtype,
  :parent_node => node,
  :child_nodes => child_nodes
} %>
<% if node.get_partial_name %>
  <%= render :partial => '/tree_display/actions/'+node.get_partial_name,
    :locals => {:id => node.node_object_id} %>
<% else %>
  <%= render :partial=> '/tree_display/actions/no_actions' %>
<% end %>
<%= render :partial => 'row_footer',
  :locals => {
  :depth => depth,
  :prefix => prefix,
  :parent_node => node,
  :child_nodes => child_nodes
} %>

app/views/tree_display/_page_footer.html.erb
<% if @child_nodes.length > 0 %>
  <table id="theTable" width="80%" cell="5">
    <tr id="header"><th colspan="5" width="70%">Details</th><th width="10%">Actions</th></tr>
    <%
      index = 1
    @child_nodes.each do |node|
      if index % 2 == 0
        rowtype = "odd"
      else
        rowtype = "even"
      end
    %>
  <!-- Start Listing -->
  <%= render :partial=> '/tree_display/entry', :locals => {:search => @search, :node => node, :prefix => node.node_object_id.to_s+"_"+index.to_s, :depth => 0, :rowtype => rowtype} %>
  <!-- End Listing -->
  <%
      index+=1
    end
  %>
</table>
<% end %>

app/views/tree_display/_page_header.html.erb
<BR/>
<%= form_tag({:action => 'list'}) do %>
  <TABLE width="80%">
    <TR>
      <TD width="50%" align="right">
        Sort by:
        <select name='display[sortvar]' style="width: 10em">
          <option value='name'
          <% if @sortvar == 'name' %>selected
          <% end %>>name
          </option>
          <option value='created_at'
          <% if @sortvar == 'created_at' %>selected
          <% end %>>date created
          </option>
          <option value='updated_at'
          <% if @sortvar == 'updated_at' %>selected
          <% end %>>date updated
          </option>
          <option value='directory_path'
          <% if @sortvar == 'directory_path' %>selected
          <% end %>>directory path
          </option>
        </select>
        <select name='display[sortorder]' style="width: 10em">
          <option value='desc'
          <% if @sortorder == 'desc' %>selected
          <% end %>>descending
          </option>
          <option value='asc'
          <% if @sortorder == 'asc' %>selected
          <% end %>>ascending
          </option>
        </select>
      </TD>
      <TD width="5%" align="left"><%= submit_tag "Sort" %></TD>
    </TR>
    Search: &nbsp;

    <%= label_tag(:search_string, "") %>
    <%= text_field_tag(:search_string) %>
    in

    <select name='searchnode' style="width: 10em">
      <option value='Q'
      <% if @searchnode == 'Q' %>selected
      <% end %>>Questionnare
      </option>
      <option value='C'
      <% if @searchnode == 'C' %>selected
      <% end %>>Courses
      </option>
      <option value='A'
      <% if @searchnode == 'A' %>selected
      <% end %>>Assignments
      </option>
    </select>
    &nbsp; &nbsp;
    <%= submit_tag("Search") %>

    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
    <%= submit_tag("Reset") %>

    </br></br>
    Filter: &nbsp;
    <select name='filternode' style="width: 17em">
      <option value='ACN'
      <% if @filternode == 'ACN' %>selected
      <% end %>>Assignment by course name
      </option>
      <option value='QAN'
      <% if @filternode == 'QAN' %>selected
      <% end %>>Questionnare by assignment name
      </option>
    </select>
    &nbsp;
    <%= label_tag(:filter_string, "") %>
    <%= text_field_tag(:filter_string) %>
    &nbsp; &nbsp;
    <%= submit_tag("Filter") %>
  </TABLE>
  <% if @root %>
    <%= hidden_field_tag('root', @root_node.id) %>
  <% end %>
<% end %>

app/views/tree_display/_row_footer.html.erb
</TR>
<%
    if child_nodes
      index = 1
      for node in child_nodes
    %>

  <!-- Start Inner Listing -->
  <%= render :partial=> '/tree_display/entry', :locals => {:node => node, :prefix => prefix+"_"+index.to_s, :depth => depth + 1, :rowtype => rowtype } %>
  <!-- End Inner Listing -->
  <%
      index+=1
      end
    %>
<% end %>

app/views/tree_display/_row_header.html.erb
<tr
  <% if rowtype != nil %>class="<%= rowtype %>"
  <% elsif prefix != nil %>id="<%= prefix %>" style="display: none;" name="team member"
  <% end %>>
  <% if depth != nil
       index = 0
       while index < depth %>
     <td WIDTH="2%">&nbsp;</td>
     <%   index += 1
       end
  end %>
<% if parent_node.is_leaf %>
  <td WIDTH="2%">&nbsp;</td>
  <td WIDTH="2%">&nbsp;</td>
<% else %>
  <% if parent_node.get_name == 'Courses'&& session[:user].role_id == 6 %>
  <%else%>
    <% if child_nodes %>
      <td WIDTH="2%" ALIGN="RIGHT"><a id="<%= prefix %>Link" name="<%= prefix %>Link" href="#" <% if child_nodes.length > 0 %>onclick="toggleList('<%= prefix %>',<%= child_nodes.length %>);alternate('theTable');return false;"><img src="/assets/expand.png"><% else %>onclick="return false;"><img src="/assets/noaction.png"><% end %></a></td>
      <td WIDTH="2%" ALIGN="RIGHT"><%= link_to image_tag('/assets/drill.png'), :controller => 'tree_display', :action => 'drill', :root => parent_node.id %></td>
    <% end %>
  <%end%>
<% end %>
<% width = 66 - depth * 2 %>
<td COLSPAN="<%= 3 - depth %>" WIDTH="<%= width %>%">
  <% if parent_node.get_name == 'Courses'&& session[:user].role_id == 6 %>
  <%else%>
    <%= parent_node.get_name(session[:ip]) %>
    <% if parent_node.get_directory != nil%>
      <br/><I>Directory:</I> <%= parent_node.get_directory %>
  <% end %>
  <% if parent_node.get_creation_date != nil %>
    <br/><I>Creation Date:</I> <%= parent_node.get_creation_date.strftime("%F") %>
<% end %>
<% if parent_node.get_modified_date != nil %>
  <br/><I>Updated Date:</I> <%= parent_node.get_modified_date %>
        <% end %>

      <%end%>
    </td>

app/views/tree_display/confirm.html.erb
<% if @node_type == 'course' %>
    <h1>Are you sure you want to delete this course?</h1>
<% else %>
    <h1>Are you sure you want to delete this assignment?</h1>
<% end %>


<table align="center">
  <tr align="center"><tr></tr><tr></tr>
    <td align="center" width="120px" style="font-size: xx-large"><%= link_to 'NO', list_tree_display_index_url %></td>
    <td align="center" width="120px" style="font-size: xx-large">
        <% if @node_type == 'course' %>
            <%= link_to 'YES', :controller => :course, :action => :delete, :id => @id %>
        <% else %>
            <%= link_to 'YES', :controller => :assignments, :action => :delete, :id => @id %>
        <% end %>
    </td>
  </tr>
</table>

app/views/tree_display/list.html.erb
<h1>Manage content</h1>

<%= link_to 'Manage Notifications', notifications_url %>
<div id="tree_display" params="#{@reactjsParams}"></div>