config/routes.rb
  resources :admin, only: [] do
    collection do
      get :list_super_administrators
      get :list_administrators
      get :list_instructors
      post :create_instructor
      get :remove_instructor
      post :remove_instructor
      get :show_instructor
    end
  end

  resources :advertise_for_partner, only: %i[new create edit update] do
    collection do
      get :remove
      post ':id', action: :update
    end
  end

  resources :advice, only: [] do
    collection do
      post :save_advice
    end
  end

  resources :answer

  resources :answer_tags, only: [:index] do
    collection do
      post :create_edit
    end
  end

  resources :assessment360, only: [] do
    collection do
      # get :one_course_all_assignments
      get :all_students_all_reviews
      # get :one_student_all_reviews
      # get :one_assignment_all_students
    end
  end

  resources :assignments, except: [:destroy] do
    collection do
      get :associate_assignment_with_course
      get :copy
      get :toggle_access
      get :delayed_mailer
      get :list_submissions
      get :delete_delayed_mailer
      get :remove_assignment_from_course
    end
  end

  resources :badges, only: %i[new create] do
    collection do
      get :redirect_to_assignment
    end
  end

  resources :bookmarks, except: %i[index show] do
    collection do
      get :list
      post :save_bookmark_rating_score
    end
  end

  resources :content_pages do
    collection do
      get :list
      get ':page_name', action: :view
    end
  end

  resources :controller_actions do
    collection do
      get :list
      post ':id', action: :update
      get :new_for
    end
  end

  resources :course, only: %i[new create edit update] do
    collection do
      get :toggle_access
      get :copy
      get :view_teaching_assistants
      post :add_ta
      get :auto_complete_for_user_name
      post :remove_ta
    end
  end

  resources :eula, only: [] do
    collection do
      get :accept
      get :decline
      get :display
    end
  end

  resources :export_file, only: [] do
    collection do
      get :start
      get :export
      post :export
      post :exportdetails
    end
  end

  resources :grades, only: %i[edit update] do
    collection do
      get :view
      get :view_team
      get :view_reviewer
      get :view_my_scores
      get :instructor_review
      post :remove_hyperlink
      post :save_grade_and_comment_for_submission
    end
  end

  resources :impersonate, only: [] do
    collection do
      get :start
      post :impersonate
    end
  end

  resources :import_file, only: [] do
    collection do
      get :start
      get :show
      get :import
      post :show
      post :import
    end
  end

resources :institution, except: [:destroy] do
    collection do
      get :list
      post ':id', action: :update
    end
  end

  resources :invitations, only: %i[new create] do
    collection do
      get :cancel
      get :accept
      get :decline
    end
  end

  resources :join_team_requests do
    collection do
      post :decline
    end
  end

  resources :late_policies
  resources :markup_styles

  resources :menu_items do
    collection do
      get :move_down
      get :move_up
      get :new_for
      get :link
      get :list
    end
  end

  resources :notifications

  resources :participants, only: [:destroy] do
    collection do
      get :add
      post :add
      get :auto_complete_for_user_name
      get :delete_assignment_participant
      get :list
      get :change_handle
      get :inherit
      get :bequeath_all
      get :inherit
      get :bequeath_all
      post :update_authorizations
      post :update_duties
      post :change_handle
      get :view_publishing_rights
    end
  end

  resources :password_retrieval, only: [] do
    collection do
      get :forgotten
      get :reset_password
      post :send_password
      post :update_password
    end
  end

  resources :profile, only: %i[edit update]

  resources :publishing, only: [] do
    collection do
      get :view
      post :update_publish_permissions
      post :set_publish_permission
      get :grant
      get :grant_with_private_key
      post :grant_with_private_key
      get :set_publish_permission
    end
  end

  resources :questionnaires, only: %i[new create edit update] do
    collection do
      get :copy
      get :list
      post :list_questionnaires
      get :new_quiz
      get :select_questionnaire_type
      post :select_questionnaire_type
      get :toggle_access
      get :view
      post :create_quiz_questionnaire
      post :update_quiz
      post :add_new_questions
      post :save_all_questions
    end
  end

  resources :author_feedback_questionnaires, controller: :questionnaires
  resources :review_questionnaires, controller: :questionnaires
  resources :metareview_questionnaires, controller: :questionnaires
  resources :teammate_review_questionnaires, controller: :questionnaires
  resources :survey_questionnaires, controller: :questionnaires
  resources :assignment_survey_questionnaires, controller: :questionnaires
  resources :global_survey_questionnaires, controller: :questionnaires
  resources :course_survey_questionnaires, controller: :questionnaires
  resources :bookmarkrating_questionnaires, controller: :questionnaires

  resources :questions do
    collection do
      get :types
    end
  end

  resources :reputation_web_service, only: [] do
    collection do
      get :client
      post :send_post_request
    end
  end

  resources :response, only: %i[new create edit update] do
    collection do
      get :new_feedback
      get :view
      get :remove_hyperlink
      get :saving
      get :redirection
      get :show_calibration_results_for_student
      post :custom_create
      get :pending_surveys
      get :json
    end
  end

  resources :review_mapping, only: [] do
    collection do
      post :add_metareviewer
      get :add_reviewer
      post :add_reviewer
      post :add_self_reviewer
      get :add_self_reviewer
      get :add_user_to_assignment
      get :auto_complete_for_user_name
      get :delete_all_metareviewers
      get :delete_outstanding_reviewers
      get :delete_metareviewer
      get :delete_reviewer
      get :distribution
      get :list_mappings
      get :response_report
      post :response_report
      get :select_metareviewer
      get :select_reviewer
      get :select_mapping
      post :assign_quiz_dynamically
      get :assign_reviewer_dynamically
      post :assign_reviewer_dynamically
      get :assign_metareviewer_dynamically
      post :assign_metareviewer_dynamically
      post :automatic_review_mapping
      post :automatic_review_mapping_staggered
      # E1600
      post :start_self_review
      post :save_grade_and_comment_for_reviewer
      get :unsubmit_review
    end
  end

  resources :roles do
    collection do
      get :list
      post ':id', action: :update
    end
  end

  resources :sign_up_sheet, except: %i[index show] do
    collection do
      get :signup
      get :delete_signup
      get :add_signup_topics
      get :add_signup_topics_staggered
      get :delete_signup
      get :list
      get :signup_topics
      get :signup
      get :sign_up
      get :team_details
      get :intelligent_sign_up
      get :intelligent_save
      get :signup_as_instructor
      post :signup_as_instructor_action
      post :set_priority
      post :save_topic_deadlines
    end
  end

  resources :site_controllers do
    collection do
      get :list
      get :new_called
    end
  end

  resources :student_quizzes, only: [:index] do
    collection do
      post :student_quizzes
      post :record_response
      get :finished_quiz
      get :take_quiz
      get :review_questions
    end
  end

  resources :student_review, only: [] do
    collection do
      get :list
    end
  end

  resources :student_task, only: [] do
    collection do
      get :list
      get :view
      get '/*other', to: redirect('/student_task/list')
    end
  end

  resources :student_teams, only: %i[create edit update] do
    collection do
      get :view
      get :remove_participant
      get :auto_complete_for_user_name
    end
  end

  resources :submitted_content, only: [:edit] do
    collection do
      get :download
      get :folder_action
      get :remove_hyperlink
      post :remove_hyperlink
      get :submit_file
      post :submit_file
      post :folder_action
      post :submit_hyperlink
      get :submit_hyperlink
      get :view
    end
  end

  resources :submission_records, only: [:index]

  resources :suggestion, only: %i[show new create] do
    collection do
      get :list
      post :submit
      post :student_submit
      post :update_suggestion
    end
  end

  resources :survey_deployment, only: %i[new create] do
    collection do
      get :list
      get :reminder_thread
    end
  end

  resources :system_settings do
    collection do
      get :list
    end
  end

  resources :teams, only: %i[new create edit update] do
    collection do
      get :list
      # post ':id', action: :create_teams
      post :create_teams
      post :inherit
    end
  end

  resources :teams_users, only: %i[new create] do
    collection do
      post :list
    end
  end

  resources :tag_prompts, except: %i[new edit]
  resources :track_notifications, only: [:index]

  resources :tree_display, only: [] do
    collection do
      get :action
      post :list
      post :children_node_ng
      post :children_node_2_ng
      post :bridge_to_is_available
      get :session_last_open_tab
      get :set_session_last_open_tab
    end
  end

  resources :users, constraints: {id: /\d+/} do
    collection do
      get :list
      post :list
      get :list_pending_requested
      post ':id', action: :update
      get :show_selection
      get :auto_complete_for_user_name
      get :set_anonymized_view
      get :keys
      post :create_requested_user_record
      post :create_approved_user

app/helpers/participants_helper.rb
module ParticipantsHelper
  # separates the file into the necessary elements to create a new user
  def self.upload_users(filename, session, params, home_page)
    users = []
    File.open(filename, "r") do |infile|
      while (rline = infile.gets)
        config = get_config
        attributes = define_attributes(rline.split(config["dlm"]), config)
        users << define_user(attributes, session, params, home_page)
      end
    end
    users
  end

  def self.define_attributes(line_split, config)
    attributes = {}
    attributes["role_id"] = Role.find_by name: "Student"
    attributes["name"] = line_split[config["name"].to_i]
    attributes["fullname"] = config["fullname"]
    attributes["email"] = line_split[config["email"].to_i]
    attributes["password"] = assign_password(8)
    attributes["email_on_submission"] = 1
    attributes["email_on_review"] = 1
    attributes["email_on_review_of_review"] = 1
    attributes
  end

  def self.define_user(attrs, session, params, home_page)
    user = User.find_by(name: attrs["name"])
    user = create_new_user(attrs, session) if user.nil?
    if !params[:course_id].nil?
      participant = add_user_to_course(params, user)
    elsif !params[:assignment_id].nil?
      participant = add_user_to_assignment(params, user)
    end
    participant.email(attrs["password"], home_page) unless participant.nil?
    user
  end

  def self.create_new_user(attrs, session)
    user = User.new
    user.update_attributes attrs
    user.parent_id = (session[:user]).id
    user.save
    user
  end

  def self.add_user_to_assignment(params, user)
    assignment = Assignment.find params[:assignment_id]
    if AssignmentParticipant.where('user_id = ? AND parent_id = ?', user.id, assignment.id).empty?
      return AssignmentParticipant.create(parent_id: assignment.id, user_id: user.id)
    end
  end

  def self.add_user_to_course(params, user)
    if CourseParticipant.where('user_id = ? AND parent_id = ?', user.id, params[:course_id]).empty?
      CourseParticipant.create(user_id: user.id, parent_id: params[:course_id])
    end
  end

  def self.get_config
    config = {}
    cfgdir = Rails.root + "/config/"
    File.open(cfgdir + "roster_config", "r") do |infile|
      while (line = infile.gets)
        store_item(line, "dlm", config)
        store_item(line, "name", config)
        store_item(line, "fullname", config)
        store_item(line, "email", config)
      end
    end
    config
  end

  def self.store_item(line, ident, config)
    line_split = line.split("=")
    if line_split[0] == ident
      newstr = line_split[1].sub!("\n", "")
      config[ident] = newstr.strip unless newstr.nil?
    end
  end
end

app/views/participants/_participant.html.erb
<% userid << participant.user_id %>
<tr class= "" style="font-size: 15px">
  <td ><%= link_to participant.user.name(session[:ip]), impersonate_impersonate_path(:user => {:name => participant.user.name(session[:ip])}), :method => :post %></td>
  <td ><%= link_to participant.user.fullname(session[:ip]), :controller=> 'users', :action => 'show', :id => participant.user_id %></td>
  <td><a href="mailto: <%= participant.user.email(session[:ip]) %>"><%= participant.user.email(session[:ip]) %></a></td>
  <td><%= participant.user.role.name %></td>
  <td align = "left"><%= (User.find(participant.user.parent_id)).name(session[:ip]) %></td>
  <% if participant.assignment.has_badge? %>
    <td align = "left"><%= get_awarded_badges(participant) %></td>
  <% end %>
  <td align = "left"><%= User.yesorno(participant.user.email_on_review) %></td>
  <td align = "left"><%= User.yesorno(participant.user.email_on_submission) %></td>
  <td align = "left"><%= User.yesorno(participant.user.email_on_review_of_review) %></td>
  <td align = "left"><%= participant.can_submit == false ? 'no' : 'yes' %></td>
  <td align = "left"><%= participant.can_review == false ? 'no' : 'yes' %></td>
  <td align = "left"><%= participant.can_take_quiz == false ? 'no' : 'yes' %></td>
  <td align = "left"><%= participant.handle(session[:ip]) %></td>

  <td align="left" ><%= link_to 'Remove', {:controller => controller, :action => 'destroy', :id => participant.id}, :method => :delete %></td>

  <!-- E726 Fall2012 Changes Begin -->
  <% authorization = Participant.get_authorization(participant.can_submit, participant.can_review, participant.can_take_quiz) %>
  <% if authorization =='reader' %>
      <td><%= fa_icon 'book', title: 'reader' %></td>
  <% else %>
      <td></td>
  <% end %>
  <!-- E726 Fall2012 Changes End -->

  <td>
    <%= form_tag :controller=>'participants', :action=>'update_authorizations', :id => participant.id do %>
        <% params[:authorization] = authorization %>
        <select class="form-control" id=<%=participant.user_id%> name="authorization" style="font-size:15px">

          <option value="participant"
                  <% if params[:authorization] == "participant" -%>
                  selected
                  <% end -%>
                  >participant</option>
          <option value="reader"
                  <% if params[:authorization] == "reader" -%>
                  selected
                  <% end -%>
                  >reader</option>
          <option value="reviewer"
                  <% if params[:authorization] == "reviewer" -%>
                  selected
                  <% end -%>
                  >reviewer</option>
          <option value="submitter"
                  <% if params[:authorization] == "submitter" -%>
                  selected
                  <% end -%>
                  >submitter</option>
        </select>
        <%= button_tag "Submit", {:id=>'button'+participant.user_id.to_s,:style=>"font-size:15px; display:none;", :class => "btn btn-md btn-default" } %>
    <% end %>
  </td>

</tr>

app/views/participants/add.js.erb
// E1721: Adding AJAX for adding participants to assignment
<% unless flash[:error] %>
$("#plist").append(
	"<%= j render :partial => 'participant', :locals => {participant: @participant, :userid => @participant.user_id, :controller => 'participants'} %>");
<% end %>
+$("#flash_message").html("<%= j render partial: "shared/flash_messages" %>");

app/views/participants/change_handle.html.erb
<h1>Create or Change Handle for Current Assignment</h1>

<%= form_tag({:action => 'change_handle', :id =>  @participant}) do %>
  <p>Your <strong>handle</strong> is the way you will be known to your reviewers.</p>
  <p>For example, if you are writing on a wiki, you might not want to use your Expertiza user-ID to show up on the
    wiki, because then your reviewers would know who they are reviewing. So, you are allowed to set up a handle instead.
    If you have a handle, then your wiki account is named after your handle, and your reviewers see your handle,
    but not your user-ID.</p>
  <p>If you do not have a handle, your user-ID will be used instead.</p>
  <p>You can set up a handle in two ways:
    <ol><li>You can set up a handle for <em>only this assignment</em> by entering a handle below.</li>
      <li>You can set up a "default" handle by editing your <%= link_to "Profile", :controller=> 'profile', :action => 'edit' %> </li></ol>
    Note that if you change your handle by editing your <%= link_to "profile", :controller=> 'profile', :action => 'edit' %>, your new handle will be used for all <em>future</em> assignments;
    if you want the change to apply to this assignment too, you must also change it below.
  </p>
  <p>Change handle <em>for current assignment</em>:
    <%= text_field 'participant','handle' %>

    <p><em>Warning:</em> You must have a wiki account named after your handle.  If you do not, please e-mail your instructor or the course staff.</p>
    <%= submit_tag 'Save' %>
  <% end %>

app/views/participants/list.html.erb
<div id="flash_message"></div>
<h1><%= @model %> Participants: <%= @parent.name %></h1>

<br/>
<div id="part_list" >
<%= render :partial => '/shared_scripts/user_list',
           :locals => {:controller => 'participants', 
                       :user_list => @participants} %>
<br/>
</div>
<%= 
	render :partial => '/shared_scripts/add_individual',
		   :locals => {:form_action => "add",
                   :remote => true,
					   :obj_type => "id", 
					   :obj_id => @parent.id,
					   :model => @model,
                       :authorization => @authorization}
%>
<br/>
<% session[:return_to] = request.url %>
<% if params[:model] == 'Assignment' and @parent.course_id and  @parent.course_id > 0 %>
  <%= link_to 'Copy participants from course', :action => 'inherit', :id => @root_node.node_object_id %>  |
  <%= link_to 'Copy participants to course', :action => 'bequeath_all', :id => @root_node.node_object_id %><BR/>
<% end %>
<%= link_to 'Import '+@model.to_s.downcase+' participants',
            :controller=>'import_file', 
            :action=>'start', 
            :model => @model+'Participant', 
            :title => @model+' Participants',
            :expected_fields => 'username&nbsp;&nbsp;|&nbsp;&nbsp;full name (first [middle] last)&nbsp;&nbsp;|&nbsp;&nbsp;e-mail address&nbsp;&nbsp;|&nbsp;&nbsp;password',
            :id => @parent.id %> | 
<%= link_to 'Export '+@model.to_s.downcase+' participants',
            :controller=>'export_file',
            :action=>'start',
            :model=>@model+'Participant',
            :id=>@parent.id %> |
<%= render :partial => '/shared_scripts/back' %>
<hr/>

app/views/participants/select.html.erb
<h1>Assignments</h1>

<table>
  <tr><th>Title</th><th>Directory Path</th></tr>
  <% for assignment in @assignments %>
    <tr>
      <td><%= link_to assignment.name, :action => 'list',
        :id => assignment.id %>&nbsp;&nbsp;</td>
      <td><%= assignment.directory_path %></td>
    </tr>
  <% end -%>
</table>

app/views/participants/view_publishing_rights.html.erb
<h1>Publishing rights for <%= @assignment_name %> assignment</h1>

<% if flash[:notice] %>
    <div class="flash_note"><%= flash[:notice] %></div>
<% end %>

<table class="general">
    <tr>
        <% if @has_topics %>
            <th width="5%" rowspan="2">Topic #</th>
            <th width="40" rowspan="2">Topic name(s)</th>
        <% end %>
        <th width="20%" rowspan="2">Team name</th>
        <th width="35%" colspan="4">Participant</th>
    </tr>
    <tr>
        <th>Name</th>
        <th>Fullname</th>
        <th>Publish Rights</th>
        <th>Verified</th>
    </tr>

    <% @teams_info.each do |team_info| %>
        <% 
            users = team_info[:users]
            num_students = users.size 
        %>        
        <tr>
            <% if @has_topics %>
                <td rowspan="<%= num_students %>"><%= team_info[:topic_id] %> </td>
                <td rowspan="<%= num_students %>"><%= team_info[:topic_name] %></td>
            <% end %> 
            <td align="center" rowspan="<%= num_students %>">
                <b><%= team_info[:name] %></b> 
            </td>
            
            <% users.each do |user| %>
                <td> <%=user[:name]%> </td>
                <td> <%=user[:fullname]%> </td>
                <td> <%=user[:pub_rights]%> </td>
                <td>
                    <% if user[:verfied] %>
                        <img src="/assets/Check-icon.png" title="verified with digitigal signature" alt="verified"/>
                    <% else %>
                        <img src="/assets/delete_icon.png" title="no digitigal signature" alt="unverified"/>
                    <% end %>
                </td> </tr><tr>
            <% end %>

        </tr>

    <% end %>
</table>

    