config/routes.rb
Expertiza::Application.routes.draw do
  ###
  # Please insert new routes alphabetically!
  ###
  resources :admin, only: [] do
    collection do
      get :list_super_administrators
      get :list_administrators
      get :list_instructors
      post :create_instructor
      get :remove_instructor
      post :remove_instructor
      get :show_instructor
    end
  end

  resources :advertise_for_partner, only: %i[new create edit update] do
    collection do
      get :remove
      post ':id', action: :update
    end
  end

  resources :advice, only: [] do
    collection do
      post :save_advice
    end
  end

  resources :answer

  resources :answer_tags, only: [:index] do
    collection do
      post :create_edit
    end
  end

  resources :assessment360, only: [] do
    collection do
      # get :one_course_all_assignments
      get :all_students_all_reviews
      # get :one_student_all_reviews
      # get :one_assignment_all_students
    end
  end

  resources :assignments, except: [:destroy] do
    collection do
      get :associate_assignment_with_course
      get :copy
      get :toggle_access
      get :delayed_mailer
      get :list_submissions
      get :delete_delayed_mailer
      get :remove_assignment_from_course
    end
  end

  resources :badges, only: %i[new create] do
    collection do
      get :redirect_to_assignment
    end
  end

  resources :bookmarks, except: %i[index show] do
    collection do
      get :list
      post :save_bookmark_rating_score
    end
  end

  resources :content_pages do
    collection do
      get :list
      get ':page_name', action: :view
    end
  end

  resources :controller_actions do
    collection do
      get :list
      post ':id', action: :update
      get :new_for
    end
  end

  resources :course, only: %i[new create edit update] do
    collection do
      get :toggle_access
      get :copy
      get :view_teaching_assistants
      post :add_ta
      get :auto_complete_for_user_name
      post :remove_ta
    end
  end

  resources :eula, only: [] do
    collection do
      get :accept
      get :decline
      get :display
    end
  end

  resources :export_file, only: [] do
    collection do
      get :start
      get :export
      post :export
      post :exportdetails
    end
  end

  resources :grades, only: %i[edit update] do
    collection do
      get :view
      get :view_team
      get :view_reviewer
      get :view_my_scores
      get :instructor_review
      post :remove_hyperlink
      post :save_grade_and_comment_for_submission
    end
  end

  resources :impersonate, only: [] do
    collection do
      get :start
      post :impersonate
    end
  end

  resources :import_file, only: [] do
    collection do
      get :start
      get :show
      get :import
      post :show
      post :import
    end
  end

resources :institution, except: [:destroy] do
    collection do
      get :list
      post ':id', action: :update
    end
  end

  resources :invitations, only: %i[new create] do
    collection do
      get :cancel
      get :accept
      get :decline
    end
  end

  resources :join_team_requests do
    collection do
      post :decline
    end
  end

  resources :late_policies
  resources :markup_styles

  resources :menu_items do
    collection do
      get :move_down
      get :move_up
      get :new_for
      get :link
      get :list
    end
  end

  resources :notifications

  resources :participants, only: [:destroy] do
    collection do
      get :add
      post :add
      get :auto_complete_for_user_name
      get :delete_assignment_participant
      get :list
      get :change_handle
      get :inherit
      get :bequeath_all
      get :inherit
      get :bequeath_all
      post :update_authorizations
      post :update_duties
      post :change_handle
      get :view_publishing_rights
    end
  end

  resources :password_retrieval, only: [] do
    collection do
      get :forgotten
      get :reset_password
      post :send_password
      post :update_password
    end
  end

  resources :profile, only: %i[edit update]

  resources :publishing, only: [] do
    collection do
      get :view
      post :update_publish_permissions
      post :set_publish_permission
      get :grant
      get :grant_with_private_key
      post :grant_with_private_key
      get :set_publish_permission
    end
  end

  resources :questionnaires, only: %i[new create edit update] do
    collection do
      get :copy
      get :list
      post :list_questionnaires
      get :new_quiz
      get :select_questionnaire_type
      post :select_questionnaire_type
      get :toggle_access
      get :view
      post :create_quiz_questionnaire
      post :update_quiz
      post :add_new_questions
      post :save_all_questions
    end
  end

  resources :author_feedback_questionnaires, controller: :questionnaires
  resources :review_questionnaires, controller: :questionnaires
  resources :metareview_questionnaires, controller: :questionnaires
  resources :teammate_review_questionnaires, controller: :questionnaires
  resources :survey_questionnaires, controller: :questionnaires
  resources :assignment_survey_questionnaires, controller: :questionnaires
  resources :global_survey_questionnaires, controller: :questionnaires
  resources :course_survey_questionnaires, controller: :questionnaires
  resources :bookmarkrating_questionnaires, controller: :questionnaires

  resources :questions do
    collection do
      get :types
    end
  end

  resources :reputation_web_service, only: [] do
    collection do
      get :client
      post :send_post_request
    end
  end

  resources :response, only: %i[new create edit update] do
    collection do
      get :new_feedback
      get :view
      get :remove_hyperlink
      get :saving
      get :redirection
      get :show_calibration_results_for_student
      post :custom_create
      get :pending_surveys
      get :json
    end
  end

  resources :review_mapping, only: [] do
    collection do
      post :add_metareviewer
      get :add_reviewer
      post :add_reviewer
      post :add_self_reviewer
      get :add_self_reviewer
      get :add_user_to_assignment
      get :auto_complete_for_user_name
      get :delete_all_metareviewers
      get :delete_outstanding_reviewers
      get :delete_metareviewer
      get :delete_reviewer
      get :distribution
      get :list_mappings
      get :response_report
      post :response_report
      get :select_metareviewer
      get :select_reviewer
      get :select_mapping
      post :assign_quiz_dynamically
      get :assign_reviewer_dynamically
      post :assign_reviewer_dynamically
      get :assign_metareviewer_dynamically
      post :assign_metareviewer_dynamically
      post :automatic_review_mapping
      post :automatic_review_mapping_staggered
      # E1600
      post :start_self_review
      post :save_grade_and_comment_for_reviewer
      get :unsubmit_review
    end
  end

  resources :roles do
    collection do
      get :list
      post ':id', action: :update
    end
  end

  resources :sign_up_sheet, except: %i[index show] do
    collection do
      get :signup
      get :delete_signup
      get :add_signup_topics
      get :add_signup_topics_staggered
      get :delete_signup
      get :list
      get :signup_topics
      get :signup
      get :sign_up
      get :team_details
      get :intelligent_sign_up
      get :intelligent_save
      get :signup_as_instructor
      post :signup_as_instructor_action
      post :set_priority
      post :save_topic_deadlines
    end
  end

  resources :site_controllers do
    collection do
      get :list
      get :new_called
    end
  end

  resources :student_quizzes, only: [:index] do
    collection do
      post :student_quizzes
      post :record_response
      get :finished_quiz
      get :take_quiz
      get :review_questions
    end
  end

  resources :student_review, only: [] do
    collection do
      get :list
    end
  end

  resources :student_task, only: [] do
    collection do
      get :list
      get :view
      get '/*other', to: redirect('/student_task/list')
    end
  end

  resources :student_teams, only: %i[create edit update] do
    collection do
      get :view
      get :remove_participant
      get :auto_complete_for_user_name
    end
  end

  resources :submitted_content, only: [:edit] do
    collection do
      get :download
      get :folder_action
      get :remove_hyperlink
      post :remove_hyperlink
      get :submit_file
      post :submit_file
      post :folder_action
      post :submit_hyperlink
      get :submit_hyperlink
      get :view
    end
  end

  resources :submission_records, only: [:index]

  resources :suggestion, only: %i[show new create] do
    collection do
      get :list
      post :submit
      post :student_submit
      post :update_suggestion
    end
  end

  resources :survey_deployment, only: %i[new create] do
    collection do
      get :list
      get :reminder_thread
    end
  end

  resources :system_settings do
    collection do
      get :list
    end
  end

  resources :teams, only: %i[new create edit update] do
    collection do
      get :list
      # post ':id', action: :create_teams
      post :create_teams
      post :inherit
    end
  end

  resources :teams_users, only: %i[new create] do
    collection do
      post :list
    end
  end

  resources :tag_prompts, except: %i[new edit]
  resources :track_notifications, only: [:index]

  resources :tree_display, only: [] do
    collection do
      get :action
      post :list
      post :children_node_ng
      post :children_node_2_ng
      post :bridge_to_is_available
      get :session_last_open_tab
      get :set_session_last_open_tab
    end
  end

  resources :users, constraints: {id: /\d+/} do
    collection do
      get :list
      post :list
      get :list_pending_requested
      post ':id', action: :update
      get :show_selection
      get :auto_complete_for_user_name

app/models/join_team_request.rb
class JoinTeamRequest < ActiveRecord::Base
  belongs_to :team
  has_one :participant
end

app/controllers/join_team_requests_controller.rb
class JoinTeamRequestsController < ApplicationController
  before_action :check_team_status, only: [:create]
  before_action :find_request, only: %i[show edit update destroy decline]

  def action_allowed?
    current_role_name.eql?("Student")
  end

  def index
    @join_team_requests = JoinTeamRequest.all
    respond_after @join_team_requests
  end

  def show
    respond_after @join_team_request
  end

  def new
    @join_team_request = JoinTeamRequest.new
    respond_after @join_team_request
  end

  def edit; end

  # create a new join team request entry for join_team_request table and add it to the table
  def create
    @join_team_request = JoinTeamRequest.new
    @join_team_request.comments = params[:comments]
    @join_team_request.status = 'P'
    @join_team_request.team_id = params[:team_id]

    participant = Participant.where(user_id: session[:user][:id], parent_id: params[:assignment_id]).first
    @join_team_request.participant_id = participant.id
    respond_to do |format|
      if @join_team_request.save
        format.html { redirect_to(@join_team_request, notice: 'JoinTeamRequest was successfully created.') }
        format.xml  { render xml: @join_team_request, status: :created, location: @join_team_request }
      else
        format.html { render action: "new" }
        format.xml  { render xml: @join_team_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # update join team request entry for join_team_request table and add it to the table
  def update
    respond_to do |format|
      if @join_team_request.update_attribute(:comments, params[:join_team_request][:comments])
        format.html { redirect_to(@join_team_request, notice: 'JoinTeamRequest was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render action: "edit" }
        format.xml  { render xml: @join_team_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @join_team_request.destroy

    respond_to do |format|
      format.html { redirect_to(join_team_requests_url) }
      format.xml  { head :ok }
    end
  end

  # decline request to join the team...
  def decline
    @join_team_request.status = 'D'
    @join_team_request.save
    redirect_to view_student_teams_path student_id: params[:teams_user_id]
  end

  private

  def check_team_status
    # check if the advertisement is from a team member and if so disallow requesting invitations
    team_member = TeamsUser.where(['team_id =? and user_id =?', params[:team_id], session[:user][:id]])
    team = Team.find(params[:team_id])
    return flash[:error] = "This team is full." if team.full?
    return flash[:error] = "You are already a member of this team." unless team_member.empty?
  end

  def find_request
    @join_team_request = JoinTeamRequest.find(params[:id])
  end

  def respond_after(request)
    respond_to do |format|
      format.html
      format.xml { render xml: request }
    end
  end
end

app/helpers/join_team_requests_helper.rb
module JoinTeamRequestsHelper
  def display_request_status(join_team_request)
    status = case join_team_request.status
             when 'P'
               'Pending: A request has been made to join this team.'
             when 'D'
               'Denied: The team has denied your request.'
             when 'A'
               "Accepted: The team has accepted your request.\nYou should receive an invitation in \"Your Team\" page."
             else
               join_team_request.status
    end
    status
  end
end

app/views/join_team_requests/_list_received.html.erb
<% @join_team_requests = JoinTeamRequest.where(team_id: team_id) %>
<% if !@join_team_requests.empty? %>
<h2>Received Requests</h2>
<table style="width:80%" align="center" >
  <tr style="border: 1px outset #000000; ">
    <th class="head">Name</th>
    <th class="head">Comments</th>
    <th class="head">Action</th>
    <th class="head">Sent at</th>
  </tr>

    <% @join_team_requests.each do |join_team_request| %>
      <% if join_team_request.status=='P' %>
        <tr>

          <td>
            <%= User.find(Participant.find(join_team_request.participant_id).user_id).name %>
          </td>
          <td>
            <%= join_team_request.comments %>
          </td>
          <td>
            <table>
              <tr>
                <td>
                  <%= form_tag :controller => 'invitations', :action => 'create' do %>
                    <%= hidden_field_tag 'team_id', team_id %>
                    <%= hidden_field_tag 'student_id', teams_user_id %>
                    <%= hidden_field_tag 'session[:dummy][:assignment_id]', Participant.find(join_team_request.participant_id).parent_id %>
                    <%= hidden_field_tag 'user[name]', User.find(Participant.find(join_team_request.participant_id).user_id).name %>
                    <%= hidden_field_tag 'participant_id', join_team_request.participant_id %>
                    <input type='submit' value='Invite'/>
                  <% end %>
                </td>
                <td>
                  <%= button_to 'Decline', :controller => 'join_team_requests', :action => 'decline', :id=>join_team_request.id, :teams_user_id=>teams_user_id %>
                </td>
              </tr>
            </table>

          </td>
          <td>
            <%= join_team_request.created_at %>
          </td>
        </tr>
      <% end %>

    <% end %>

  <% end %>
</table>

app/views/join_team_requests/_list_sent.html.erb
<% participant = Participant.where(user_id: session[:user].id, parent_id:  assignment_id).first
   requests=JoinTeamRequest.where(participant_id: participant.id) %>
<% if !requests.empty? %>

<h2>Sent Requests </h2>
<table style="width:80%" align="center" >
    <tr style="border: 1px outset #000000; ">
      <th class="head">Team</th>
      <th class="head">Comments</th>
      <th class="head">Status</th>
      <th class="head">Sent at</th>
   </tr>

  <% requests.each do |request| %>

    <tr>
      <td>
        <% if Team.exists?(request.team_id)==false  %>
          <font color="#FF0000">  This team no longer exists. </font>
        <% else %>
          <%= Team.find(request.team_id).name %>
        <% end %>
      </td>
      <td>
        <%= request.comments %>
      </td>
      <td>
        <% if request.status == 'P' %>
          <%= "Pending" %>
        <% elsif request.status == 'A' %>
          <%= "Accepted" %>
        <% else %>
          <%= "Declined"  %>
        <% end %>
      </td>
      <td>
        <%= request.created_at %>
      </td>
    </tr>
  <% end %>

<% end %>
  </table>

app/views/join_team_requests/edit.html.erb
<h1>Editing join_team_request</h1>

<%= form_for(@join_team_request) do |f| %>
  <%= f.error_messages %>

  <%= f.hidden_field :participant_id %>
  <%= f.hidden_field :team_id %>
  <%= f.hidden_field :status %>
  <p>
    <%= f.text_area :comments %>
  </p>

  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @join_team_request %> |
<%= link_to 'Back', join_team_requests_path %>

app/views/join_team_requests/new.html.erb
<h1>Sending request to join team "<%= Team.find(params[:team_id]).name %>" </h1>
<%= form_tag :action => 'create', :assignment_id=>params[:assignment_id],:team_id=>params[:team_id],:controller => 'join_team_requests' do %>
  <%= form_for(@join_team_request) do |f| %>
    <p>
      <b>Desired Qualification</b>   <br>
      <%= Team.find(params[:team_id]).comments_for_advertisement %>
    </p>
    <p>
      <p>Comments <img src="/assets/info.png" title="Please specify why you are qualified."></p>
      <br>
      <%= text_area 'comments', "" %>
    </p>
    <p>
      <%= f.submit 'Create' %>
    </p>
  <% end %>
<% end %>

app/views/join_team_requests/show.html.erb
<p>
  <b>Team:</b> <br>
  <%=h Team.find_by(id: @join_team_request.team_id).try(:name) %>
</p>

<p>
  <b>Comments:</b>  <br>
  <%=h @join_team_request.comments %>
</p>

<p>
  <b>Status:</b>  <br>
  <%= display_request_status(@join_team_request) %>
</p>

<%= link_to "Edit Comment", action: 'edit' %>